// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model.security;

import ar.org.crear.publicador.common.model.security.LogUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LogUser_Roo_Configurable {
    
    declare @type: LogUser: @Configurable;
    
}
