// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.Medio;
import ar.org.crear.publicador.common.model.MedioDataOnDemand;
import ar.org.crear.publicador.server.repository.MedioRepository;
import ar.org.crear.publicador.server.service.MedioService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MedioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MedioDataOnDemand: @Component;
    
    private Random MedioDataOnDemand.rnd = new SecureRandom();
    
    private List<Medio> MedioDataOnDemand.data;
    
    @Autowired
    MedioService MedioDataOnDemand.medioService;
    
    @Autowired
    MedioRepository MedioDataOnDemand.medioRepository;
    
    public Medio MedioDataOnDemand.getNewTransientMedio(int index) {
        Medio obj = new Medio();
        setDescripcion(obj, index);
        setTipo(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void MedioDataOnDemand.setDescripcion(Medio obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public void MedioDataOnDemand.setTipo(Medio obj, int index) {
        String tipo = "tipo_" + index;
        if (tipo.length() > 20) {
            tipo = tipo.substring(0, 20);
        }
        obj.setTipo(tipo);
    }
    
    public void MedioDataOnDemand.setUrl(Medio obj, int index) {
        String url = "url_" + index;
        if (url.length() > 500) {
            url = url.substring(0, 500);
        }
        obj.setUrl(url);
    }
    
    public Medio MedioDataOnDemand.getSpecificMedio(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Medio obj = data.get(index);
        Long id = obj.getId();
        return medioService.findMedio(id);
    }
    
    public Medio MedioDataOnDemand.getRandomMedio() {
        init();
        Medio obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return medioService.findMedio(id);
    }
    
    public boolean MedioDataOnDemand.modifyMedio(Medio obj) {
        return false;
    }
    
    public void MedioDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = medioService.findMedioEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Medio' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Medio>();
        for (int i = 0; i < 10; i++) {
            Medio obj = getNewTransientMedio(i);
            try {
                medioService.saveMedio(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            medioRepository.flush();
            data.add(obj);
        }
    }
    
}
