// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.MedioAlerta;
import ar.org.crear.publicador.common.model.MedioAlertaDataOnDemand;
import ar.org.crear.publicador.server.repository.MedioAlertaRepository;
import ar.org.crear.publicador.server.service.MedioAlertaService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MedioAlertaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MedioAlertaDataOnDemand: @Component;
    
    private Random MedioAlertaDataOnDemand.rnd = new SecureRandom();
    
    private List<MedioAlerta> MedioAlertaDataOnDemand.data;
    
    @Autowired
    MedioAlertaService MedioAlertaDataOnDemand.medioAlertaService;
    
    @Autowired
    MedioAlertaRepository MedioAlertaDataOnDemand.medioAlertaRepository;
    
    public MedioAlerta MedioAlertaDataOnDemand.getNewTransientMedioAlerta(int index) {
        MedioAlerta obj = new MedioAlerta();
        setDescripcion(obj, index);
        return obj;
    }
    
    public void MedioAlertaDataOnDemand.setDescripcion(MedioAlerta obj, int index) {
        String descripcion = "descripcion_" + index;
        obj.setDescripcion(descripcion);
    }
    
    public MedioAlerta MedioAlertaDataOnDemand.getSpecificMedioAlerta(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        MedioAlerta obj = data.get(index);
        Long id = obj.getId();
        return medioAlertaService.findMedioAlerta(id);
    }
    
    public MedioAlerta MedioAlertaDataOnDemand.getRandomMedioAlerta() {
        init();
        MedioAlerta obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return medioAlertaService.findMedioAlerta(id);
    }
    
    public boolean MedioAlertaDataOnDemand.modifyMedioAlerta(MedioAlerta obj) {
        return false;
    }
    
    public void MedioAlertaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = medioAlertaService.findMedioAlertaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'MedioAlerta' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<MedioAlerta>();
        for (int i = 0; i < 10; i++) {
            MedioAlerta obj = getNewTransientMedioAlerta(i);
            try {
                medioAlertaService.saveMedioAlerta(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            medioAlertaRepository.flush();
            data.add(obj);
        }
    }
    
}
