// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.MedioDataOnDemand;
import ar.org.crear.publicador.common.model.MedioIntegrationTest;
import ar.org.crear.publicador.server.repository.MedioRepository;
import ar.org.crear.publicador.server.service.MedioService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MedioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MedioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MedioIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MedioIntegrationTest: @Transactional;
    
    @Autowired
    MedioDataOnDemand MedioIntegrationTest.dod;
    
    @Autowired
    MedioService MedioIntegrationTest.medioService;
    
    @Autowired
    MedioRepository MedioIntegrationTest.medioRepository;
    
    @Test
    public void MedioIntegrationTest.testCountAllMedios() {
        Assert.assertNotNull("Data on demand for 'Medio' failed to initialize correctly", dod.getRandomMedio());
        long count = medioService.countAllMedios();
        Assert.assertTrue("Counter for 'Medio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MedioIntegrationTest.testFindMedio() {
        Medio obj = dod.getRandomMedio();
        Assert.assertNotNull("Data on demand for 'Medio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Medio' failed to provide an identifier", id);
        obj = medioService.findMedio(id);
        Assert.assertNotNull("Find method for 'Medio' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Medio' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MedioIntegrationTest.testFindAllMedios() {
        Assert.assertNotNull("Data on demand for 'Medio' failed to initialize correctly", dod.getRandomMedio());
        long count = medioService.countAllMedios();
        Assert.assertTrue("Too expensive to perform a find all test for 'Medio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Medio> result = medioService.findAllMedios();
        Assert.assertNotNull("Find all method for 'Medio' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Medio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MedioIntegrationTest.testFindMedioEntries() {
        Assert.assertNotNull("Data on demand for 'Medio' failed to initialize correctly", dod.getRandomMedio());
        long count = medioService.countAllMedios();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Medio> result = medioService.findMedioEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Medio' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Medio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MedioIntegrationTest.testFlush() {
        Medio obj = dod.getRandomMedio();
        Assert.assertNotNull("Data on demand for 'Medio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Medio' failed to provide an identifier", id);
        obj = medioService.findMedio(id);
        Assert.assertNotNull("Find method for 'Medio' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMedio(obj);
        Integer currentVersion = obj.getVersion();
        medioRepository.flush();
        Assert.assertTrue("Version for 'Medio' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MedioIntegrationTest.testUpdateMedioUpdate() {
        Medio obj = dod.getRandomMedio();
        Assert.assertNotNull("Data on demand for 'Medio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Medio' failed to provide an identifier", id);
        obj = medioService.findMedio(id);
        boolean modified =  dod.modifyMedio(obj);
        Integer currentVersion = obj.getVersion();
        Medio merged = medioService.updateMedio(obj);
        medioRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Medio' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MedioIntegrationTest.testSaveMedio() {
        Assert.assertNotNull("Data on demand for 'Medio' failed to initialize correctly", dod.getRandomMedio());
        Medio obj = dod.getNewTransientMedio(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Medio' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Medio' identifier to be null", obj.getId());
        try {
            medioService.saveMedio(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        medioRepository.flush();
        Assert.assertNotNull("Expected 'Medio' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MedioIntegrationTest.testDeleteMedio() {
        Medio obj = dod.getRandomMedio();
        Assert.assertNotNull("Data on demand for 'Medio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Medio' failed to provide an identifier", id);
        obj = medioService.findMedio(id);
        medioService.deleteMedio(obj);
        medioRepository.flush();
        Assert.assertNull("Failed to remove 'Medio' with identifier '" + id + "'", medioService.findMedio(id));
    }
    
}
