// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.NotificacionDataOnDemand;
import ar.org.crear.publicador.common.model.NotificacionIntegrationTest;
import ar.org.crear.publicador.server.repository.NotificacionRepository;
import ar.org.crear.publicador.server.service.NotificacionService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NotificacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NotificacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NotificacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NotificacionIntegrationTest: @Transactional;
    
    @Autowired
    NotificacionDataOnDemand NotificacionIntegrationTest.dod;
    
    @Autowired
    NotificacionService NotificacionIntegrationTest.notificacionService;
    
    @Autowired
    NotificacionRepository NotificacionIntegrationTest.notificacionRepository;
    
    @Test
    public void NotificacionIntegrationTest.testCountAllNotificacions() {
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to initialize correctly", dod.getRandomNotificacion());
        long count = notificacionService.countAllNotificacions();
        Assert.assertTrue("Counter for 'Notificacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NotificacionIntegrationTest.testFindNotificacion() {
        Notificacion obj = dod.getRandomNotificacion();
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to provide an identifier", id);
        obj = notificacionService.findNotificacion(id);
        Assert.assertNotNull("Find method for 'Notificacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Notificacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NotificacionIntegrationTest.testFindAllNotificacions() {
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to initialize correctly", dod.getRandomNotificacion());
        long count = notificacionService.countAllNotificacions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Notificacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Notificacion> result = notificacionService.findAllNotificacions();
        Assert.assertNotNull("Find all method for 'Notificacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Notificacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NotificacionIntegrationTest.testFindNotificacionEntries() {
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to initialize correctly", dod.getRandomNotificacion());
        long count = notificacionService.countAllNotificacions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Notificacion> result = notificacionService.findNotificacionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Notificacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Notificacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NotificacionIntegrationTest.testFlush() {
        Notificacion obj = dod.getRandomNotificacion();
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to provide an identifier", id);
        obj = notificacionService.findNotificacion(id);
        Assert.assertNotNull("Find method for 'Notificacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNotificacion(obj);
        Integer currentVersion = obj.getVersion();
        notificacionRepository.flush();
        Assert.assertTrue("Version for 'Notificacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NotificacionIntegrationTest.testUpdateNotificacionUpdate() {
        Notificacion obj = dod.getRandomNotificacion();
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to provide an identifier", id);
        obj = notificacionService.findNotificacion(id);
        boolean modified =  dod.modifyNotificacion(obj);
        Integer currentVersion = obj.getVersion();
        Notificacion merged = notificacionService.updateNotificacion(obj);
        notificacionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Notificacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NotificacionIntegrationTest.testSaveNotificacion() {
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to initialize correctly", dod.getRandomNotificacion());
        Notificacion obj = dod.getNewTransientNotificacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Notificacion' identifier to be null", obj.getId());
        try {
            notificacionService.saveNotificacion(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        notificacionRepository.flush();
        Assert.assertNotNull("Expected 'Notificacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NotificacionIntegrationTest.testDeleteNotificacion() {
        Notificacion obj = dod.getRandomNotificacion();
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notificacion' failed to provide an identifier", id);
        obj = notificacionService.findNotificacion(id);
        notificacionService.deleteNotificacion(obj);
        notificacionRepository.flush();
        Assert.assertNull("Failed to remove 'Notificacion' with identifier '" + id + "'", notificacionService.findNotificacion(id));
    }
    
}
