// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.MedioAlertaDataOnDemand;
import ar.org.crear.publicador.common.model.Objetivo;
import ar.org.crear.publicador.common.model.ObjetivoDataOnDemand;
import ar.org.crear.publicador.common.model.PeriodicidadDataOnDemand;
import ar.org.crear.publicador.server.repository.ObjetivoRepository;
import ar.org.crear.publicador.server.service.ObjetivoService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ObjetivoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ObjetivoDataOnDemand: @Component;
    
    private Random ObjetivoDataOnDemand.rnd = new SecureRandom();
    
    private List<Objetivo> ObjetivoDataOnDemand.data;
    
    @Autowired
    MedioAlertaDataOnDemand ObjetivoDataOnDemand.medioAlertaDataOnDemand;
    
    @Autowired
    PeriodicidadDataOnDemand ObjetivoDataOnDemand.periodicidadDataOnDemand;
    
    @Autowired
    ObjetivoService ObjetivoDataOnDemand.objetivoService;
    
    @Autowired
    ObjetivoRepository ObjetivoDataOnDemand.objetivoRepository;
    
    public Objetivo ObjetivoDataOnDemand.getNewTransientObjetivo(int index) {
        Objetivo obj = new Objetivo();
        setMaximo(obj, index);
        setMinimo(obj, index);
        return obj;
    }
    
    public void ObjetivoDataOnDemand.setMaximo(Objetivo obj, int index) {
        Integer maximo = new Integer(index);
        obj.setMaximo(maximo);
    }
    
    public void ObjetivoDataOnDemand.setMinimo(Objetivo obj, int index) {
        Integer minimo = new Integer(index);
        obj.setMinimo(minimo);
    }
    
    public Objetivo ObjetivoDataOnDemand.getSpecificObjetivo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Objetivo obj = data.get(index);
        Long id = obj.getId();
        return objetivoService.findObjetivo(id);
    }
    
    public Objetivo ObjetivoDataOnDemand.getRandomObjetivo() {
        init();
        Objetivo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return objetivoService.findObjetivo(id);
    }
    
    public boolean ObjetivoDataOnDemand.modifyObjetivo(Objetivo obj) {
        return false;
    }
    
    public void ObjetivoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = objetivoService.findObjetivoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Objetivo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Objetivo>();
        for (int i = 0; i < 10; i++) {
            Objetivo obj = getNewTransientObjetivo(i);
            try {
                objetivoService.saveObjetivo(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            objetivoRepository.flush();
            data.add(obj);
        }
    }
    
}
