// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.PeriodicidadDataOnDemand;
import ar.org.crear.publicador.common.model.PeriodicidadIntegrationTest;
import ar.org.crear.publicador.server.repository.PeriodicidadRepository;
import ar.org.crear.publicador.server.service.PeriodicidadService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PeriodicidadIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PeriodicidadIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PeriodicidadIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PeriodicidadIntegrationTest: @Transactional;
    
    @Autowired
    PeriodicidadDataOnDemand PeriodicidadIntegrationTest.dod;
    
    @Autowired
    PeriodicidadService PeriodicidadIntegrationTest.periodicidadService;
    
    @Autowired
    PeriodicidadRepository PeriodicidadIntegrationTest.periodicidadRepository;
    
    @Test
    public void PeriodicidadIntegrationTest.testCountAllPeriodicidads() {
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to initialize correctly", dod.getRandomPeriodicidad());
        long count = periodicidadService.countAllPeriodicidads();
        Assert.assertTrue("Counter for 'Periodicidad' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PeriodicidadIntegrationTest.testFindPeriodicidad() {
        Periodicidad obj = dod.getRandomPeriodicidad();
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to provide an identifier", id);
        obj = periodicidadService.findPeriodicidad(id);
        Assert.assertNotNull("Find method for 'Periodicidad' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Periodicidad' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PeriodicidadIntegrationTest.testFindAllPeriodicidads() {
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to initialize correctly", dod.getRandomPeriodicidad());
        long count = periodicidadService.countAllPeriodicidads();
        Assert.assertTrue("Too expensive to perform a find all test for 'Periodicidad', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Periodicidad> result = periodicidadService.findAllPeriodicidads();
        Assert.assertNotNull("Find all method for 'Periodicidad' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Periodicidad' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PeriodicidadIntegrationTest.testFindPeriodicidadEntries() {
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to initialize correctly", dod.getRandomPeriodicidad());
        long count = periodicidadService.countAllPeriodicidads();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Periodicidad> result = periodicidadService.findPeriodicidadEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Periodicidad' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Periodicidad' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PeriodicidadIntegrationTest.testFlush() {
        Periodicidad obj = dod.getRandomPeriodicidad();
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to provide an identifier", id);
        obj = periodicidadService.findPeriodicidad(id);
        Assert.assertNotNull("Find method for 'Periodicidad' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPeriodicidad(obj);
        Integer currentVersion = obj.getVersion();
        periodicidadRepository.flush();
        Assert.assertTrue("Version for 'Periodicidad' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PeriodicidadIntegrationTest.testUpdatePeriodicidadUpdate() {
        Periodicidad obj = dod.getRandomPeriodicidad();
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to provide an identifier", id);
        obj = periodicidadService.findPeriodicidad(id);
        boolean modified =  dod.modifyPeriodicidad(obj);
        Integer currentVersion = obj.getVersion();
        Periodicidad merged = periodicidadService.updatePeriodicidad(obj);
        periodicidadRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Periodicidad' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PeriodicidadIntegrationTest.testSavePeriodicidad() {
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to initialize correctly", dod.getRandomPeriodicidad());
        Periodicidad obj = dod.getNewTransientPeriodicidad(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Periodicidad' identifier to be null", obj.getId());
        try {
            periodicidadService.savePeriodicidad(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        periodicidadRepository.flush();
        Assert.assertNotNull("Expected 'Periodicidad' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PeriodicidadIntegrationTest.testDeletePeriodicidad() {
        Periodicidad obj = dod.getRandomPeriodicidad();
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Periodicidad' failed to provide an identifier", id);
        obj = periodicidadService.findPeriodicidad(id);
        periodicidadService.deletePeriodicidad(obj);
        periodicidadRepository.flush();
        Assert.assertNull("Failed to remove 'Periodicidad' with identifier '" + id + "'", periodicidadService.findPeriodicidad(id));
    }
    
}
