// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.PublicacionDataOnDemand;
import ar.org.crear.publicador.common.model.PublicacionIntegrationTest;
import ar.org.crear.publicador.server.service.PublicacionService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PublicacionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PublicacionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PublicacionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PublicacionIntegrationTest: @Transactional;
    
    @Autowired
    PublicacionDataOnDemand PublicacionIntegrationTest.dod;
    
    @Autowired
    PublicacionService PublicacionIntegrationTest.publicacionService;
    
    @Test
    public void PublicacionIntegrationTest.testCountAllPublicacions() {
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to initialize correctly", dod.getRandomPublicacion());
        long count = publicacionService.countAllPublicacions();
        Assert.assertTrue("Counter for 'Publicacion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PublicacionIntegrationTest.testFindPublicacion() {
        Publicacion obj = dod.getRandomPublicacion();
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to provide an identifier", id);
        obj = publicacionService.findPublicacion(id);
        Assert.assertNotNull("Find method for 'Publicacion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Publicacion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PublicacionIntegrationTest.testFindAllPublicacions() {
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to initialize correctly", dod.getRandomPublicacion());
        long count = publicacionService.countAllPublicacions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Publicacion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Publicacion> result = publicacionService.findAllPublicacions();
        Assert.assertNotNull("Find all method for 'Publicacion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Publicacion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PublicacionIntegrationTest.testFindPublicacionEntries() {
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to initialize correctly", dod.getRandomPublicacion());
        long count = publicacionService.countAllPublicacions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Publicacion> result = publicacionService.findPublicacionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Publicacion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Publicacion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PublicacionIntegrationTest.testFlush() {
        Publicacion obj = dod.getRandomPublicacion();
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to provide an identifier", id);
        obj = publicacionService.findPublicacion(id);
        Assert.assertNotNull("Find method for 'Publicacion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPublicacion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Publicacion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PublicacionIntegrationTest.testUpdatePublicacionUpdate() {
        Publicacion obj = dod.getRandomPublicacion();
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to provide an identifier", id);
        obj = publicacionService.findPublicacion(id);
        boolean modified =  dod.modifyPublicacion(obj);
        Integer currentVersion = obj.getVersion();
        Publicacion merged = publicacionService.updatePublicacion(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Publicacion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PublicacionIntegrationTest.testSavePublicacion() {
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to initialize correctly", dod.getRandomPublicacion());
        Publicacion obj = dod.getNewTransientPublicacion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Publicacion' identifier to be null", obj.getId());
        try {
            publicacionService.savePublicacion(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Publicacion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PublicacionIntegrationTest.testDeletePublicacion() {
        Publicacion obj = dod.getRandomPublicacion();
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Publicacion' failed to provide an identifier", id);
        obj = publicacionService.findPublicacion(id);
        publicacionService.deletePublicacion(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Publicacion' with identifier '" + id + "'", publicacionService.findPublicacion(id));
    }
    
}
