// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.PublicacionDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PublicacionDataOnDemand_Roo_Configurable {
    
    declare @type: PublicacionDataOnDemand: @Configurable;
    
}
