// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.TareaProgramadaDataOnDemand;
import ar.org.crear.publicador.common.model.TareaProgramadaIntegrationTest;
import ar.org.crear.publicador.server.repository.TareaProgramadaRepository;
import ar.org.crear.publicador.server.service.TareaProgramadaService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TareaProgramadaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TareaProgramadaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TareaProgramadaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TareaProgramadaIntegrationTest: @Transactional;
    
    @Autowired
    TareaProgramadaDataOnDemand TareaProgramadaIntegrationTest.dod;
    
    @Autowired
    TareaProgramadaService TareaProgramadaIntegrationTest.tareaProgramadaService;
    
    @Autowired
    TareaProgramadaRepository TareaProgramadaIntegrationTest.tareaProgramadaRepository;
    
    @Test
    public void TareaProgramadaIntegrationTest.testCountAllTareaProgramadas() {
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to initialize correctly", dod.getRandomTareaProgramada());
        long count = tareaProgramadaService.countAllTareaProgramadas();
        Assert.assertTrue("Counter for 'TareaProgramada' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TareaProgramadaIntegrationTest.testFindTareaProgramada() {
        TareaProgramada obj = dod.getRandomTareaProgramada();
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to provide an identifier", id);
        obj = tareaProgramadaService.findTareaProgramada(id);
        Assert.assertNotNull("Find method for 'TareaProgramada' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TareaProgramada' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TareaProgramadaIntegrationTest.testFindAllTareaProgramadas() {
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to initialize correctly", dod.getRandomTareaProgramada());
        long count = tareaProgramadaService.countAllTareaProgramadas();
        Assert.assertTrue("Too expensive to perform a find all test for 'TareaProgramada', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TareaProgramada> result = tareaProgramadaService.findAllTareaProgramadas();
        Assert.assertNotNull("Find all method for 'TareaProgramada' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TareaProgramada' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TareaProgramadaIntegrationTest.testFindTareaProgramadaEntries() {
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to initialize correctly", dod.getRandomTareaProgramada());
        long count = tareaProgramadaService.countAllTareaProgramadas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TareaProgramada> result = tareaProgramadaService.findTareaProgramadaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TareaProgramada' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TareaProgramada' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TareaProgramadaIntegrationTest.testFlush() {
        TareaProgramada obj = dod.getRandomTareaProgramada();
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to provide an identifier", id);
        obj = tareaProgramadaService.findTareaProgramada(id);
        Assert.assertNotNull("Find method for 'TareaProgramada' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTareaProgramada(obj);
        Integer currentVersion = obj.getVersion();
        tareaProgramadaRepository.flush();
        Assert.assertTrue("Version for 'TareaProgramada' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TareaProgramadaIntegrationTest.testUpdateTareaProgramadaUpdate() {
        TareaProgramada obj = dod.getRandomTareaProgramada();
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to provide an identifier", id);
        obj = tareaProgramadaService.findTareaProgramada(id);
        boolean modified =  dod.modifyTareaProgramada(obj);
        Integer currentVersion = obj.getVersion();
        TareaProgramada merged = tareaProgramadaService.updateTareaProgramada(obj);
        tareaProgramadaRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TareaProgramada' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TareaProgramadaIntegrationTest.testSaveTareaProgramada() {
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to initialize correctly", dod.getRandomTareaProgramada());
        TareaProgramada obj = dod.getNewTransientTareaProgramada(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TareaProgramada' identifier to be null", obj.getId());
        try {
            tareaProgramadaService.saveTareaProgramada(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        tareaProgramadaRepository.flush();
        Assert.assertNotNull("Expected 'TareaProgramada' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TareaProgramadaIntegrationTest.testDeleteTareaProgramada() {
        TareaProgramada obj = dod.getRandomTareaProgramada();
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TareaProgramada' failed to provide an identifier", id);
        obj = tareaProgramadaService.findTareaProgramada(id);
        tareaProgramadaService.deleteTareaProgramada(obj);
        tareaProgramadaRepository.flush();
        Assert.assertNull("Failed to remove 'TareaProgramada' with identifier '" + id + "'", tareaProgramadaService.findTareaProgramada(id));
    }
    
}
