// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.TareaProgramada;
import ar.org.crear.publicador.common.model.TareaProgramadaDataOnDemand;
import ar.org.crear.publicador.server.repository.TareaProgramadaRepository;
import ar.org.crear.publicador.server.service.TareaProgramadaService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TareaProgramadaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TareaProgramadaDataOnDemand: @Component;
    
    private Random TareaProgramadaDataOnDemand.rnd = new SecureRandom();
    
    private List<TareaProgramada> TareaProgramadaDataOnDemand.data;
    
    @Autowired
    TareaProgramadaService TareaProgramadaDataOnDemand.tareaProgramadaService;
    
    @Autowired
    TareaProgramadaRepository TareaProgramadaDataOnDemand.tareaProgramadaRepository;
    
    public TareaProgramada TareaProgramadaDataOnDemand.getNewTransientTareaProgramada(int index) {
        TareaProgramada obj = new TareaProgramada();
        return obj;
    }
    
    public TareaProgramada TareaProgramadaDataOnDemand.getSpecificTareaProgramada(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TareaProgramada obj = data.get(index);
        Long id = obj.getId();
        return tareaProgramadaService.findTareaProgramada(id);
    }
    
    public TareaProgramada TareaProgramadaDataOnDemand.getRandomTareaProgramada() {
        init();
        TareaProgramada obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return tareaProgramadaService.findTareaProgramada(id);
    }
    
    public boolean TareaProgramadaDataOnDemand.modifyTareaProgramada(TareaProgramada obj) {
        return false;
    }
    
    public void TareaProgramadaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = tareaProgramadaService.findTareaProgramadaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TareaProgramada' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TareaProgramada>();
        for (int i = 0; i < 10; i++) {
            TareaProgramada obj = getNewTransientTareaProgramada(i);
            try {
                tareaProgramadaService.saveTareaProgramada(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            tareaProgramadaRepository.flush();
            data.add(obj);
        }
    }
    
}
