// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.Tema;
import ar.org.crear.publicador.common.model.TemaDataOnDemand;
import ar.org.crear.publicador.server.repository.TemaRepository;
import ar.org.crear.publicador.server.service.TemaService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TemaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TemaDataOnDemand: @Component;
    
    private Random TemaDataOnDemand.rnd = new SecureRandom();
    
    private List<Tema> TemaDataOnDemand.data;
    
    @Autowired
    TemaService TemaDataOnDemand.temaService;
    
    @Autowired
    TemaRepository TemaDataOnDemand.temaRepository;
    
    public Tema TemaDataOnDemand.getNewTransientTema(int index) {
        Tema obj = new Tema();
        return obj;
    }
    
    public Tema TemaDataOnDemand.getSpecificTema(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Tema obj = data.get(index);
        Long id = obj.getId();
        return temaService.findTema(id);
    }
    
    public Tema TemaDataOnDemand.getRandomTema() {
        init();
        Tema obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return temaService.findTema(id);
    }
    
    public boolean TemaDataOnDemand.modifyTema(Tema obj) {
        return false;
    }
    
    public void TemaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = temaService.findTemaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Tema' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Tema>();
        for (int i = 0; i < 10; i++) {
            Tema obj = getNewTransientTema(i);
            try {
                temaService.saveTema(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            temaRepository.flush();
            data.add(obj);
        }
    }
    
}
