// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.org.crear.publicador.common.model;

import ar.org.crear.publicador.common.model.TemaDataOnDemand;
import ar.org.crear.publicador.common.model.TemaIntegrationTest;
import ar.org.crear.publicador.server.repository.TemaRepository;
import ar.org.crear.publicador.server.service.TemaService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TemaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TemaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TemaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TemaIntegrationTest: @Transactional;
    
    @Autowired
    TemaDataOnDemand TemaIntegrationTest.dod;
    
    @Autowired
    TemaService TemaIntegrationTest.temaService;
    
    @Autowired
    TemaRepository TemaIntegrationTest.temaRepository;
    
    @Test
    public void TemaIntegrationTest.testCountAllTemas() {
        Assert.assertNotNull("Data on demand for 'Tema' failed to initialize correctly", dod.getRandomTema());
        long count = temaService.countAllTemas();
        Assert.assertTrue("Counter for 'Tema' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TemaIntegrationTest.testFindTema() {
        Tema obj = dod.getRandomTema();
        Assert.assertNotNull("Data on demand for 'Tema' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tema' failed to provide an identifier", id);
        obj = temaService.findTema(id);
        Assert.assertNotNull("Find method for 'Tema' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tema' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TemaIntegrationTest.testFindAllTemas() {
        Assert.assertNotNull("Data on demand for 'Tema' failed to initialize correctly", dod.getRandomTema());
        long count = temaService.countAllTemas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tema', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tema> result = temaService.findAllTemas();
        Assert.assertNotNull("Find all method for 'Tema' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tema' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TemaIntegrationTest.testFindTemaEntries() {
        Assert.assertNotNull("Data on demand for 'Tema' failed to initialize correctly", dod.getRandomTema());
        long count = temaService.countAllTemas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tema> result = temaService.findTemaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tema' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tema' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TemaIntegrationTest.testFlush() {
        Tema obj = dod.getRandomTema();
        Assert.assertNotNull("Data on demand for 'Tema' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tema' failed to provide an identifier", id);
        obj = temaService.findTema(id);
        Assert.assertNotNull("Find method for 'Tema' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTema(obj);
        Integer currentVersion = obj.getVersion();
        temaRepository.flush();
        Assert.assertTrue("Version for 'Tema' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TemaIntegrationTest.testUpdateTemaUpdate() {
        Tema obj = dod.getRandomTema();
        Assert.assertNotNull("Data on demand for 'Tema' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tema' failed to provide an identifier", id);
        obj = temaService.findTema(id);
        boolean modified =  dod.modifyTema(obj);
        Integer currentVersion = obj.getVersion();
        Tema merged = temaService.updateTema(obj);
        temaRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tema' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TemaIntegrationTest.testSaveTema() {
        Assert.assertNotNull("Data on demand for 'Tema' failed to initialize correctly", dod.getRandomTema());
        Tema obj = dod.getNewTransientTema(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tema' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tema' identifier to be null", obj.getId());
        try {
            temaService.saveTema(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        temaRepository.flush();
        Assert.assertNotNull("Expected 'Tema' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TemaIntegrationTest.testDeleteTema() {
        Tema obj = dod.getRandomTema();
        Assert.assertNotNull("Data on demand for 'Tema' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tema' failed to provide an identifier", id);
        obj = temaService.findTema(id);
        temaService.deleteTema(obj);
        temaRepository.flush();
        Assert.assertNull("Failed to remove 'Tema' with identifier '" + id + "'", temaService.findTema(id));
    }
    
}
